#!/usr/bin/env python3
"""embed-fonts.py -- subset the UI font and write it into the binary.

    python scripts/embed-fonts.py <fonts dir>

The fonts dir holds the full TTFs, from github.com/google/fonts (ofl/) and
github.com/lucide-icons/lucide (releases); their licences are in vendor/fonts/:
    inter.ttf          Inter[opsz,wght].ttf; pinned here to Regular
    noto-math.ttf      NotoSansMath-Regular.ttf; the symbols Inter lacks
    lucide.ttf         the icons below
Inter is cut to every glyph it has in TEXT_RANGES; the SYMBOLS it lacks come
from Noto Sans Math; hinting is dropped (stb_truetype does not use it). Writes
src/font_data.c (the bytes) and src/icons.h (the glyph ranges for the atlas, and
a UTF-8 string per icon). Needs fonttools (pip install fonttools).
"""
import io, os, sys
from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

TEXT_RANGES = [
    (0x0020, 0x007E), (0x00A0, 0x017F),   # ASCII, Latin-1, Latin Extended-A
    (0x0370, 0x03FF),                     # Greek
    (0x2010, 0x205E),                     # dashes, quotes, bullets, primes, per mille
    (0x2070, 0x209F), (0x20AC, 0x20AC),   # super- and subscripts, euro
    (0x2100, 0x214F),                     # letterlike: degree Celsius, ohm, angstrom
    (0x2190, 0x21FF),                     # arrows
    (0x2200, 0x22FF),                     # mathematical operators
    (0x2300, 0x23FF),                     # technical: diameter
    (0x25A0, 0x25FF),                     # geometric shapes
    (0x2713, 0x2713), (0x2717, 0x2717),   # check, cross
]
# must render: taken from Noto Sans Math where Inter has no glyph
SYMBOLS = "∂∇∞≈≠≡≤≥≪≫∑∏√∛∫∮∝∠⊥∥∈∉∀∃∅∪∩⊂⊃⊆⊇∧∨¬⊗⊕∓×÷·°±′″→←↑↓↔⇒⇔⌀Δ∆Ω℃µ"
ICONS = ["folder-open", "rotate-cw", "play", "pause", "step-back", "step-forward",
         "chevron-left", "chevron-right", "scan", "camera", "video", "eye", "eye-off",
         "crosshair", "ruler", "settings", "download", "file", "x", "check", "info",
         "palette", "chart-line", "film", "save", "search", "box", "list"]

def load(path):
    font = TTFont(path)
    if "fvar" in font:                    # stb_truetype has no variations: pin Regular
        loc = {a.axisTag: (400 if a.axisTag == "wght" else a.defaultValue) for a in font["fvar"].axes}
        font = instancer.instantiateVariableFont(font, loc)
    return font

def subset_font(font, unicodes):
    opts = subset.Options()
    opts.hinting = False
    opts.layout_features = []
    opts.desubroutinize = True
    opts.notdef_outline = True
    opts.name_IDs = [0, 1, 2, 4, 5, 6, 13, 14]   # keep copyright, names, licence (OFL)
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=unicodes)
    sub.subset(font)
    out = io.BytesIO()
    font.save(out)
    return out.getvalue()

def runs(cps):
    """sorted codepoints as (first, last) runs"""
    r = []
    for c in sorted(cps):
        if r and c == r[-1][1] + 1: r[-1][1] = c
        else: r.append([c, c])
    return r

def c_array(name, data):
    lines = [f"const unsigned char {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 20):
        lines.append("    " + ",".join(str(b) for b in data[i:i + 20]) + ",")
    lines.append("};")
    lines.append(f"const unsigned {name}_size = {len(data)};")
    return "\n".join(lines)

def c_ranges(name, cps):
    return f"#define {name} " + ", ".join(f"0x{a:04X},0x{b:04X}" for a, b in runs(cps))

def main():
    src = sys.argv[1]
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
    parts = ["/* font_data.c -- generated by scripts/embed-fonts.py; do not edit.",
             "   Subsets of Inter and Noto Sans Math (OFL) and of Lucide (ISC); see vendor/fonts/. */", ""]

    inter = load(os.path.join(src, "inter.ttf"))
    have = set(inter.getBestCmap())
    text = {c for a, b in TEXT_RANGES for c in range(a, b + 1) if c in have}
    data = subset_font(inter, text)
    parts.append(c_array("cv_font_text", data))
    print(f"inter: {len(data)} bytes, {len(text)} glyphs")

    math = load(os.path.join(src, "noto-math.ttf"))
    mhave = set(math.getBestCmap())
    want = {ord(ch) for ch in SYMBOLS} - text
    lost = sorted(c for c in want if c not in mhave)
    if lost: sys.exit("no glyph for " + " ".join(f"U+{c:04X}" for c in lost))
    data = subset_font(math, want)
    parts.append(c_array("cv_font_math", data))
    print(f"noto math: {len(data)} bytes, {len(want)} glyphs: " + "".join(chr(c) for c in sorted(want)))

    lucide = TTFont(os.path.join(src, "lucide.ttf"))
    byname = {v: k for k, v in lucide.getBestCmap().items()}
    cps = [byname[n] for n in ICONS]
    data = subset_font(lucide, cps)
    parts.append(c_array("cv_font_icons", data))
    print(f"icons: {len(data)} bytes, {len(cps)} glyphs")
    with open(os.path.join(root, "src", "font_data.c"), "w", newline="\n") as o:
        o.write("\n".join(parts) + "\n")

    h = ["/* icons.h -- generated by scripts/embed-fonts.py; do not edit.",
         "   The glyph ranges of the embedded fonts, for the font atlas (each lists",
         "   only glyphs its font has: the atlas takes a codepoint from the first",
         "   range holding it). And a UTF-8 string per icon (Lucide), to put in",
         "   labels: nk_button_label(ctx, IC_PLAY \" play\"). */",
         "#ifndef CV_ICONS_H", "#define CV_ICONS_H", "",
         c_ranges("FONT_TEXT_RANGES", text),
         c_ranges("FONT_MATH_RANGES", want),
         c_ranges("FONT_ICON_RANGES", cps), ""]
    for n, cp in zip(ICONS, cps):
        u = chr(cp).encode("utf-8")
        h.append(f'#define IC_{n.upper().replace("-", "_"):<14} "' + "".join(f"\\x{b:02x}" for b in u) + f'"   /* U+{cp:04X} */')
    h.append("")
    h.append("#endif")
    with open(os.path.join(root, "src", "icons.h"), "w", newline="\n") as o:
        o.write("\n".join(h) + "\n")

main()
